---
title: "Final Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Reference Guide {.tabset .tabset-pills}

## Creating vectors
```{r}
#Create a vector of numbers:
num_vec  = c(1, 4, 8, 9, 13)

#Create a vector of characters:
char_vec = c("a", "fish", "data is cool")

#Typing the name of the vector into the console prints the contents
num_vec

## The print() function accomplishes the same task:
print(char_vec)
```

## Loading Data and Packages
```{r}
library(here)

#install package and load load package option 2 
require(palmerpenguins) #load 2

#load data into a data frame
ginkgo <- read.csv(here("data", "ginkgo_data_2021.csv"))
```

## Data Structures 
```{r}
#create a vector 
vec <- c(1,3,7,5,10,9,2,8,6)

#determine the length of an object
length(vec)

#create a matrix out of the vector data
matrix(data = vec, nrow = 3, ncol = 3)

#create a data frame from vector data
Species <- c("SB", "GD", "BT", "AS", "AT")
Treatment <- c(1, 2, 2, 1, 2)

data.frame(Species, Treatment)

#determine the number of rows in a data frame
nrow(ginkgo)

#determine the number of columns/variables in a data frame
ncol(ginkgo)

#determine the dimensions over a quicker way #rows will always show up first
dim(ginkgo)
```

## Subsetting
```{r}
#subsetting a data frame by column
ginkgo$site_id

#subset first row of data frame
ginkgo[1,]

#select the element in row 2 and column 3
ginkgo[2,3]

#select the third column of a data frame
ginkgo[,3]

#subset one species from data frame
subset(penguins, species == "Adelie")
```

## Numerical data Exploration 
```{r}
##get result summaries for every column
summary(ginkgo)

#calculate the mean of a column
mean(ginkgo$max_width)

#calculate the standard deviation of a variable + exclude NAs
sd(ginkgo$max_width, na.rm = TRUE)
```

## Graphical Data Exploration
```{r}
#using a scatterplot
plot(ginkgo$max_width~ ginkgo$max_depth,pch = 18, col= ginkgo$site_id, cex = 1, main = "Scatterplot of ginkgo leafs", xlab = "Leaf depth", ylab = "Leaf width", xlim = NULL, ylim = NULL)

#using a histogram
hist(penguins$flipper_length_mm, main = "Penguin flippers", xlab = "Flipper length", breaks = 40)

#using a boxplot
#simple boxplot
boxplot(ginkgo$petiole_length, xlab = "Petiole length", main= "Ginkgo leafs 2021") 

#notch depth conditioned on seeds present
boxplot(ginkgo$notch_depth~ginkgo$seeds_present, main = "Ginkgo leafs 2021", xlab = "Seeds present",  ylab = "Notch depth")

#four histograms 
par(mfrow= c(2,2))
hist(penguins$body_mass_g, main = "Histogram of penguin body mass", xlab = "Body mass")
hist(penguins$bill_length_mm, main = "Histogram of penguin flipper length", xlab = "Flipper length")
hist(penguins$bill_depth_mm, main = "Histogram of penguin bill depth", xlab = "Bill depth")
hist(ginkgo$max_width, main = "Histogramm of leaf width", xlab = "Leaf width")
```

## Distribution function 

```{r}
#probability density function for a continuous (normal) distribution with a mean of 2 and a sd of 2
#question: What is the probability of observing a value of 2?
dnorm(2,mean = 0, sd= 1)

#cumulative density function for a continuous (normal) distribution with a mean of 2 and a sd of 2
#question: What is the probability of observing a value greater than 1
pnorm(1,mean = 2, sd= 2, lower.tail = FALSE)

#quantile function for a continuous (normal) distribution with a mean of 2 and a sd of 2
#question: What length will 90% of all fishes will be shorter than
qnorm(0.9,mean = 2, sd= 2, lower.tail = TRUE)

#probability mass function for a discrete binomial (normal) distribution 
#question: What is the probability of observing 3 birds in 4 plots when usually birds are encountered on half of the plots?
dbinom(x= 3,size= 4, p=0.5)

#cumulative mass function for a discrete binomial (normal) distribution 
#question: What is the probability of observing 3 birds or less in 4 plots when usually birds are encountered on half of the plots?
pbinom(q=3, size=4, p=0.5, lower.tail = TRUE)

##quantile mass function for a discrete binomial (normal) distribution with
#question: What is the 10th quantile of a binomial distribution with 10 trials and a success probability of 0.4 on each trial?
qbinom(p=0.1, size = 10, prob = 0.4)
```






